# Base image
FROM node:18

# Create app directory
WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y \
        git \
        openssh-server 


# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Bundle app source

COPY . .

# Install app dependencies
RUN npm install

# Creates a "dist" folder with the production build
RUN npm run build

# Start the server using the production build
CMD [ "node", "dist/main.js" ]
