version: "3.9"

services:

  topic-sub:
    image: genixdevops/topic-subscription-microservice:latest
    container_name: topic-sub
    restart: always
    environment:
      mongodb.host: mongo
      mongodb.news.host: mongo
      mongodb.port: 27017
      mongodb.database: subscription
      mongodb.username: root
      kafka.host: kafka
      mongodb.password: example
      kafka.topics: sports:science:business:health:technology
      netty.server.port: 8085
    networks:
      tpea-network:
    links:
      - mongo
    ports:
      - 8085:8085
    depends_on:
      - mongo
      - mexpress

  aggregator:
    image: genixdevops/aggregator-services:latest
    container_name: aggregator
    restart: always
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVER_HOST: kafka
      KAFKA_BOOTSTRAP_SERVER_PORT: 9092

  news-notifier:
    image: genixdevops/news-notifier-services:latest
    container_name: news-notifier
    restart: always
    depends_on:
      - mongo
      - kafka
    volumes:
      - ./news-notifier.env:/usr/src/app/.env
    networks:
      tpea-network:
    ports:
      - 8089:3000
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
    networks:
      tpea-network:

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9094:9094
    volumes:
      - kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      tpea-network:
        
  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
    ports:
      - "8083:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
    networks:
      tpea-network:

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8082:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_READONLY=false
    networks:
      tpea-network:

  mongo:
    image: mongo
    restart: always
    hostname: mongo
    container_name : mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
    networks:
      tpea-network:

  mexpress:
    image: mongo-express
    restart: always
    container_name : mexpress
    depends_on:
      - mongo
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      tpea-network:

networks:
  tpea-network:
    name: tpea-network

volumes:
  db-data:
  mongo-data:
  kafka-data:

